// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWPt2gvpbiQX7_T1fviCqofIuUiW6pEY',
    appId: '1:1058691496583:web:04eb330d635be061f59622',
    messagingSenderId: '1058691496583',
    projectId: 'trt-smd-inventory',
    authDomain: 'trt-smd-inventory.firebaseapp.com',
    storageBucket: 'trt-smd-inventory.firebasestorage.app',
    measurementId: 'G-Q847XT2BF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuv3S99RYmFEW8AinzT4Wd3tmVJn1JobM',
    appId: '1:1058691496583:android:7043f768c099bb83f59622',
    messagingSenderId: '1058691496583',
    projectId: 'trt-smd-inventory',
    storageBucket: 'trt-smd-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59iVF_IHXGOFOCemXPUgHpDNZ5CmHPQo',
    appId: '1:1058691496583:ios:87b1d3c21b676249f59622',
    messagingSenderId: '1058691496583',
    projectId: 'trt-smd-inventory',
    storageBucket: 'trt-smd-inventory.firebasestorage.app',
    iosBundleId: 'com.example.smdInv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59iVF_IHXGOFOCemXPUgHpDNZ5CmHPQo',
    appId: '1:1058691496583:ios:87b1d3c21b676249f59622',
    messagingSenderId: '1058691496583',
    projectId: 'trt-smd-inventory',
    storageBucket: 'trt-smd-inventory.firebasestorage.app',
    iosBundleId: 'com.example.smdInv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGWPt2gvpbiQX7_T1fviCqofIuUiW6pEY',
    appId: '1:1058691496583:web:d11c2d235104b2aff59622',
    messagingSenderId: '1058691496583',
    projectId: 'trt-smd-inventory',
    authDomain: 'trt-smd-inventory.firebaseapp.com',
    storageBucket: 'trt-smd-inventory.firebasestorage.app',
    measurementId: 'G-L8FS3J5B62',
  );
}
